name: comp_venv
channels:
  - r
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=22.2.2
  - r-base=4.1.3
  - rpy2=3.5.1
  - graph-tool=2.45
  - ipython=8.4.0
  - r-data.table=1.14.2
  - r-magrittr=2.0.1
  - r-yaml=2.2.1
  - r-ggplot2=3.3.5
  - r-rcolorbrewer=1.1_2
  - r-knitr=1.39
  - r-reshape2=1.4.4
  - r-scales=1.1.1
  - r-powerlaw=0.70.6
